name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    env:
      RUST_CHANNEL: stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt
          rustup default ${{ env.RUST_CHANNEL }}
      - name: Install dependencies
        run: |
          cargo install cargo-make
          cargo make dep
      - name: Run CI taks (lint, test ...)
        run: cargo make ci
